### ISSUE TITLE
Add Topic support

### ISSUE THREAD

**Issue by spoorun** [humhub/cfiles#103]
Currently Topics can be added from the stream to files.

However, when using the Files module itself, a user cannot view, add, delete, edit, or search Topics, nor add them when creating or uploading a file.

**Comment by luke-** [comment]
@yurabakhtin The "Topic" field in the 'Edit' dialog of a file (right click / context menu) would be cool.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/cfiles/pull/124:

<img width="837" alt="file_topics" src="https://user-images.githubusercontent.com/6995524/128463965-acf8e2b3-0255-4fc4-a987-67ca2dd2cb7f.png">

**Comment by spoorun** [comment]
Great 

Will this mean that a topic can be added during the process uploading or creating a file?

Will topics be viewable/sortable when viewing file list on the files module?

**Comment by luke-** [comment]
@yurabakhtin Please see my review. I can reproduce the test error on my machine.
@spoorun No, as in other modules, the topics will only be available via the stream for the moment.

**Comment by yurabakhtin** [comment]
@luke- 

> Please see my review. I can reproduce the test error on my machine.

Thanks for the comment, it helped. Fixed in PR https://github.com/humhub/cfiles/pull/124.
