### ISSUE TITLE
Create a page to view file entry

### ISSUE THREAD

**Issue by funkycram** [humhub/cfiles#106]
## Problem

1. You receive a notification about a comment on a file.
2. Click on "View Online" button.
3. You arrive on the parent folder of the file (see https://github.com/humhub/humhub-modules-cfiles/blob/master/models/File.php#L408)

The problem is that you can potentially see dozens of files, so you do not know which file is concerned.
And you need to click on the file to see the comment.

## Proposition

Create a page to show the file entry, on the model as the wall entry wigdet does it:
![image](https://user-images.githubusercontent.com/23310825/106636077-d4c81100-6581-11eb-9024-98f213ee1ed7.png)

**Comment by luke-** [comment]
I think it's good to link to the timeline entry. 
But then we have to make sure that it exists here. (There is an option to hide individual content types).

**Comment by buddh4** [comment]
Maybe the filter should only affect stream requests and not single content requests?

**Comment by luke-** [comment]
Could be solved with this core issue:
https://github.com/humhub/humhub/issues/3442
