### ISSUE TITLE
Add Full-text-search function into Files

### ISSUE THREAD

**Issue by Vander-Ng** [humhub/cfiles#107]
The concept of adding file stores to Humhub is great, however, I think it would be even greater if there is full-text-search functions, at least applicable to certain file types such as PDF.

With this user can attach some reference materials or existing file by attaching the PDF, while other users can search the content within the File Module (if possible, it can be added to the advanced search of Humhub), so the file store would give all users the largest values.

Please kindly consider this, or you guys can make it as premium features which is chargable.

**Comment by luke-** [comment]
Have you seen this?
https://docs.humhub.org/docs/admin/search#file-content-indexing
