### ISSUE TITLE
Show thumbnails of files

### ISSUE THREAD

**Issue by spoorun** [humhub/cfiles#108]
Enable caching of thumbnails of files
Display those thumbnails when appropriate
Provide option to switch this on/off in admin settings

Related to: #103

**Comment by spoorun** [comment]
Is this a won't fix, or is there something in pipeline?
:)

**Comment by luke-** [comment]
Currently, generated thumbnail images are already cached or stored permanently.

To generate previews of other files besides images would be more then a core feature. Because PDFs etc. can also be attached to normal posts without the file module.

**Comment by luke-** [comment]
https://github.com/humhub/humhub/issues/5217

**Comment by spoorun** [comment]
> [humhub/humhub#5217](https://github.com/humhub/humhub/issues/5217)

Fairplay
(I had thought of them as separate issues, this issue being small thumbnails cached and shown if desired in the list view, to make it more attractive and more efficient - rather than full previews as per 5217)
