### ISSUE TITLE
Permissions management for Files missing from Humhub settings

### ISSUE THREAD

**Issue by spoorun** [humhub/cfiles#110]
**Issue**

Folders created within a Humhub space are not editable by other Users in the Space
It is not obvious how to easily change the setting when a) creating a file, or b) reviewing a file

**Example**

A document is created using onlyoffice plugin
The document is posted to the space
Other users in the space can download or view the document
Other users in the space cannot edit it
It is not obvious to a user how to remedy that

**See also** 
https://github.com/ONLYOFFICE/onlyoffice-humhub/issues/33

**Workaround**

Which appears to enable all users in the space to edit all files, but is not granular and not exposed in system settings

_Go to:_ 
humhub\modules\cfiles\permissions/managefiles.php

_In:_
added public $defaultAllowedGroups = [

_Add:_    
        Space::USERGROUP_MEMBER,

**Comment by luke-** [comment]
Since HumHub 1.8 the Space default permissions can be configured in the Administration.

It can be differentiated between "Every member can collaboratively edit all files" and "Every member can edit own files" depending on the role.

**Comment by niconacre** [comment]
Sorry to re.open this topic,
I can't find this parameter in Space default permission
Any update ?

**Comment by niconacre** [comment]
Thanks @marc-farre , I know this. But that's do not solve my problem wich is members can't edit document using only office connector :/

**Comment by marc-farre** [comment]
@niconacre I see. But this is an issue with the Only Office module, not this one.
