### ISSUE TITLE
PHP 8.0: Deprecate required parameters after optional parameters in function/method signatures

### ISSUE THREAD

**Issue by luke-** [humhub/cfiles#114]
Note: Also provide the full error stacks from Administration --> Information --> Logging and errors from your browser console if possible.
错误 Sun, 18 Apr 2021 09:29:31 +0000 yii\base\ErrorException:8192yii\base\ErrorException: Required parameter $params follows optional parameter $attribute in xxx/humhub/protected/modules/cfiles/models/Folder.php:599 Stack trace: #0 /xxx/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(293): yii\base\ErrorHandler->handleError(8192, 'Required parame...', '/data/data/com....', 599) #1

**Comment by luke-** [comment]
Seems with PHP 8 there is an error: https://github.com/humhub/humhub/issues/5017

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/cfiles/pull/115, but I have found similar issues in other files, I will fix them too and report below.

**Comment by yurabakhtin** [comment]
- meeting: PR https://github.com/humhub/meeting/pull/5

**Comment by luke-** [comment]
@yurabakhtin can I already check and merge the PRs?

**Comment by yurabakhtin** [comment]
@luke- I have updated my comment https://github.com/humhub/cfiles/issues/114#issuecomment-833531815 above with changes in calendar and news modules. That's all what I found, you can merge them.

**Comment by luke-** [comment]
@yurabakhtin Thank you!
