### ISSUE TITLE
Files not found

### ISSUE THREAD

**Issue by lisbonjoker** [humhub/cfiles#120]
All uploaded files are giving 
```
Oooops... It looks like you may have taken the wrong turn.
Could not find requested file!
```

**Comment by luke-** [comment]
@lisbonjoker Can you please give more infos? Do other uploads work? Are there any error messages?

**Comment by lisbonjoker** [comment]
Avatar and Banners work, but not uploads to the timelines

**Comment by luke-** [comment]
@lisbonjoker  This does not seem to be a bug with the `cfiles` module. 
If also other uploads to normal Posts fails, it seems to be more a problem with your setup.

**Comment by lisbonjoker** [comment]
> @lisbonjoker This does not seem to be a bug with the `cfiles` module.
> If also other uploads to normal Posts fails, it seems to be more a problem with your setup.

I tried to check permissions and such but nothing was incorrect
