### ISSUE TITLE
Folder Permissions For User Groups

### ISSUE THREAD

**Issue by tobiaspetrasch** [humhub/cfiles#14]
Maybe you could add a permissions feature, so folders could only be seen by specific groups. For example by admins and moderators but not for normal users.

**Comment by desertrockxxx** [comment]
+1

**Comment by vicman** [comment]
+1

**Comment by luke-** [comment]
This is more about no core restriction.

There are currently no plans to implement deeper content permissions.

There are:

Private = Members; Public = All
