### ISSUE TITLE
Tests Failing

### ISSUE THREAD

**Issue by luke-** [humhub/cfiles#144]

**Comment by yurabakhtin** [comment]
@luke- Please give me a link or branch where tests are failed, because I tested the `master` branch and it works without errors:

<img width="645" alt="cfiles_tests" src="https://user-images.githubusercontent.com/6995524/143178406-4ff9ebbf-c3da-4928-9113-08901a83e719.png">

**Comment by luke-** [comment]
@yurabakhtin https://github.com/humhub/cfiles/actions/workflows/php-test.yml

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/cfiles/pull/145.
