### ISSUE TITLE
Error with files from stream

### ISSUE THREAD

**Issue by TorWaG77** [humhub/cfiles#149]
Since cfiles 0.14.1 we have an error in the folder "files from the stream", if the stream is not empty:
`yii\base\UnknownPropertyException: Getting unknown property: humhub\modules\cfiles\models\rows\BaseFileRow::item in /var/www/humhub/protected/vendor/yiisoft/yii2/base/Component.php:155
Stack trace:
#0 /var/www/humhub/protected/modules/cfiles/widgets/views/fileSystemItem.php(46): yii\base\Component->__get()
#1 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/humhub...')
#2 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#3 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#4 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(237): yii\base\View->render()
#5 /var/www/humhub/protected/modules/cfiles/widgets/FileSystemItem.php(51): yii\base\Widget->render()
#6 /var/www/humhub/protected/humhub/components/Widget.php(63): humhub\modules\cfiles\widgets\FileSystemItem->run()
#7 /var/www/humhub/protected/modules/cfiles/widgets/views/fileList.php(55): humhub\components\Widget::widget()
#8 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/humhub...')
#9 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#10 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#11 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(237): yii\base\View->render()
#12 /var/www/humhub/protected/modules/cfiles/widgets/FileList.php(136): yii\base\Widget->render()
#13 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(141): humhub\modules\cfiles\widgets\FileList->run()
#14 /var/www/humhub/protected/modules/cfiles/widgets/views/folderView.php(29): yii\base\Widget::widget()
#15 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/humhub...')
#16 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#17 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#18 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(237): yii\base\View->render()
#19 /var/www/humhub/protected/modules/cfiles/widgets/FolderView.php(65): yii\base\Widget->render()
#20 /var/www/humhub/protected/humhub/components/Widget.php(63): humhub\modules\cfiles\widgets\FolderView->run()
#21 /var/www/humhub/protected/modules/cfiles/views/browse/index.php(36): humhub\components\Widget::widget()
#22 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/humhub...')
#23 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#24 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#25 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(410): yii\base\View->render()
#26 /var/www/humhub/protected/modules/cfiles/controllers/BrowseController.php(36): yii\base\Controller->render()
#27 [internal function]: humhub\modules\cfiles\controllers\BrowseController->actionIndex()
#28 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#29 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#30 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction()
#31 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#32 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#33 /var/www/humhub/index.php(25): yii\base\Application->run()
#34 {main}`

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/cfiles/pull/150.

**Comment by luke-** [comment]
@yurabakhtin Thanks
@TorWaG77 Fixed with 1.14.2

**Comment by TorWaG77** [comment]
@yurabakhtin Thanks for your fast work
