### ISSUE TITLE
In files tables - change icon "fa-unlock-alt" to "fa-unlock"

### ISSUE THREAD

**Issue by Gilbertdelyon** [humhub/cfiles#180]
I become old and my eyes are tired.
Please why are public files displayed with "fa-unlock-alt" icon in files tables.
I have to get close to the screen to check if it's lock or unlock.
I would highly prefer the usual simple "fa-unlock"

**Comment by luke-** [comment]
@Eladnarlea Can you please take a look into this. We should be consistent in terms of the icons.

**Comment by Eladnarlea** [comment]
![Screenshot 2023-06-12 at 11 12 49 AM](https://github.com/humhub/cfiles/assets/105652258/0c24cd79-2279-4fe0-a13b-f13f49ba6cc0)

@luke- it is actually quite inconsistent already. We use the `fa-unlock` in the menu to switch between private and public, but use the `fa-unlock-alt` within the list. Therefore changing the list icon to `fa-unlock` would be the right thing to do.

**Comment by Eladnarlea** [comment]
![Screenshot 2023-06-12 at 11 15 48 AM](https://github.com/humhub/cfiles/assets/105652258/a395cd9d-f097-470a-9702-4ed7d08d6f2c)


@yurabakhtin  can you please change the `fa-unlock-alt` to `fa-unlock` in the files list?

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/cfiles/pull/183.
