### ISSUE TITLE
Hide files in stream if the related post is on pending deletion

### ISSUE THREAD

**Issue by funkycram** [humhub/cfiles#184]
Step to reproduce:
1. Post something with a file attached
2. Delete the post
3. Go to Files -> Files from the stream: the attached file is still displayed
4. Wait for daily cron to permanent delete the post: the attached file is gone

Source: https://community.humhub.com/s/general-discussion/post/post/view?id=15711

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/cfiles/pull/185.
