### ISSUE TITLE
Possibility to rename/delete own files as space member

### ISSUE THREAD

**Issue by optitsolutions** [humhub/cfiles#195]
It woud be nice to have the ability of renaming and deleting self uploaded files with space member role.

**Comment by optitsolutions** [comment]
Can I expect a solution here in the next release or has it a low priority? thanks :-)

**Comment by yurabakhtin** [comment]
@luke- Should we implement new option "Rename" where we will allow only update file name instead of the edit modal window where all fields are allowed for editing by users with permission "Manage files"?

![edit-delete](https://github.com/humhub/cfiles/assets/6995524/e94daecf-c91e-4e3d-9672-1ae3d14d285b)

**Comment by luke-** [comment]
@yurabakhtin I think in principle it should be possible to edit/delete own files.
Is there anything against this from your point of view?

**Comment by yurabakhtin** [comment]
@luke- No, ok I will allow to edit and delete own files.

**Comment by optitsolutions** [comment]
as a normal space member I have no rights to delete my self-uploaded pics or files.
I remember that this was possible before 2 or 3 years. I cannot remember the core version or the module version.

**Comment by luke-** [comment]
@yurabakhtin Thanks. Did you remember why we changed the behavior here? It is important that the user does not have "CanManage" permission for the file but is allowed to edit/delete it.

**Comment by yurabakhtin** [comment]
@luke- 

> Did you remember why we changed the behavior here?

Sorry, not clear what exactly you mean here. In the PR https://github.com/humhub/cfiles/pull/205 I allowed editing and deleting of files and folders if current user is owner. All previous permission behavior I didn't change, i.e. if user has a permission "Manage files" then it works as before, such user can edit/move/version/delete/etc. all files.

**Comment by luke-** [comment]
@yurabakhtin I've tested and it works as expected.

**Comment by optitsolutions** [comment]
@luke- can you release this? thanks... ;-)

**Comment by luke-** [comment]
@optitsolutions Done

**Comment by optitsolutions** [comment]
thank you. I see a difference betwenn the two possible options handling a file:
![image](https://github.com/humhub/cfiles/assets/87805658/25cbfe10-f588-4f1b-a6bc-32dfcb477b95)

The current user is owner of the marked file.
Via the green marked file context menu he can delete, move,... the file.
Via the red marked drop down button he can only zip the file.
Is this behaviour as aspected?

**Comment by luke-** [comment]
@optitsolutions Hmm, can you please create a new issue for this?
