### ISSUE TITLE
Error on enabling Modul on new installation

### ISSUE THREAD

**Issue by luke-** [humhub/cfiles#210]
On a fresh humhub installation (master)

- New HumHub Installation with Files module
- Create a new space
- Enable files module during space creation

Following error appear:

![image](https://github.com/humhub/cfiles/assets/4736168/a0c02851-6187-43cb-b06b-47fdd0b69fa1)

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/cfiles/pull/212.

**Comment by Kobano8703** [comment]
Hi,

i have exactly the same exception. I want to add some information.
This happens before you can even activate the module when creating the Space. To do this, the module just needs to be activated as standart by default in the Superadmin settings when you create a Space .

kind regards
