### ISSUE TITLE
Increase File description max characters from 255 to 1000

### ISSUE THREAD

**Issue by Gilbertdelyon** [humhub/cfiles#234]
In file description you cannot enter more than 255 Characters
![image](https://github.com/user-attachments/assets/3915b8a5-2a8c-47fa-bb86-38f065e1ff00)

This could be annoying.
but in db the size of file description field is **VARCHAR(1000)**, so we could have much more than 255.

**Please, is it a bug?**

**Comment by marc-farre** [comment]
@Gilbertdelyon I agree.

@luke- PR https://github.com/humhub/cfiles/pull/235
