### ISSUE TITLE
File Edit Dialog: RichText Description

### ISSUE THREAD

**Issue by buddh4** [humhub/cfiles#48]

**Comment by luke-** [comment]
![image](https://user-images.githubusercontent.com/4736168/127669704-d786bcf0-f7b7-4328-946f-9f58870229eb.png)

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/cfiles/pull/125:

<img width="683" alt="richtext" src="https://user-images.githubusercontent.com/6995524/128466189-3050282a-d2df-48e7-800e-207026744a01.png">

**Comment by luke-** [comment]
@yurabakhtin Thanks, please see my PR comment.

**Comment by yurabakhtin** [comment]
@luke- I have answered there https://github.com/humhub/cfiles/pull/125#issuecomment-896740601.
