### ISSUE TITLE
Post files / folders with Preview

### ISSUE THREAD

**Issue by staxDB** [humhub/cfiles#57]
It would be nice to have a way to upload files / folders, that were already uploaded with cfiles, directly in the stream (or when editing a wiki article) and get a file preview.
It would also be great to display PDF files, videos, etc...
At the moment it is only possible to download the files and create a link, which you can then post.

**Comment by buddh4** [comment]
We'll introduce a new rich text with v1.3 and this feature is on the todo list, but can't promise if it will make it already to v1.3, but I think too this would be a nice feature.

**Comment by staxDB** [comment]
Ok thanks!
I guess, something like this would be possible:
![example add existing files to post](https://user-images.githubusercontent.com/8705799/37090257-e923ba4c-2203-11e8-829f-5148eb856cd2.png)

**Comment by luke-** [comment]
We plan here to either make files directly createable like a Post (above Stream) or/and also allow links between content. (e.g. CFile with post)
