### ISSUE TITLE
File History

### ISSUE THREAD

**Issue by earlpeterg** [humhub/cfiles#61]
Since uploading a file with the same name in a certain folder overwrites the file (depending on the settings), could you implement a way to view the history of changes (allowing users to download older versions) of the file? Thanks.

**Comment by staxDB** [comment]
+1

**Comment by elcarajo** [comment]
+1

**Comment by michael79bxl** [comment]
"overwriting files" is a setting, this helped me, thanks

**Comment by luke-** [comment]
https://github.com/humhub/cfiles/issues/121
