### ISSUE TITLE
Video Player popup

### ISSUE THREAD

**Issue by PaulNdrei** [humhub/cfiles#66]
At the moment only the video player with the .mp4 format shown and some more. Can something be done to work with other formats like .mov?

**Comment by staxDB** [comment]
There is currently no way to play video files in File module. Only the download is possible.

Videos will only play if they are attached to a post. That's another module.

**Comment by michael79bxl** [comment]
Could you make an option to display a video popup?

**Comment by luke-** [comment]
https://github.com/humhub/cfiles/issues/37
