### ISSUE TITLE
Hide Files in Stream

### ISSUE THREAD

**Issue by Semir1212** [humhub/cfiles#76]
It is often unnecessary to create an extra post for each upload. A checkbox when uploading a file or creating a folder that prevents this would be useful.

**Comment by olekristensen** [comment]
Just uploaded a zip and the stream is unusable, as relevant posts are over 400 down :-/

**Comment by luke-** [comment]
@olekristensen Normally, multiple subsequent files entries in the stream should be separated with a "Show more Files" to keep existing Post entries visible.
