### ISSUE TITLE
is there a way around to "move file" via php?

### ISSUE THREAD

**Issue by vpadhariya** [humhub/cfiles#79]
Hello There,

### Requirement

Download a PDF file from google and move it to some "directory" created using "cfiles"

### Problem statement

How can I execute File move from source destination to the folder destination created by "cfiles"

All this logic will be handled by "queue".

I tried "inbuilt \Zend\Http\Client" to the upload "cfile" url of space but I failed on several attempt so I want to give a try to know if there is such way possible, please help.

**Comment by buddh4** [comment]
There is no cfiles interface yet, the idea is to support external directories within the cfiles module, a google integration module could then inject a directories and files. Currently this is not possible.

**Comment by jabo59** [comment]
I suggest to think about other external directories as well: Generic Webdav, OneDrive and Nextcloud are my favorites.

**Comment by samuk** [comment]
Has there been progress on accessing external filesystems? Eg Nextcloud Webdav https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/basic.html
