### ISSUE TITLE
Field updated_at is not updated when modifying a file

### ISSUE THREAD

**Issue by caumons** [humhub/cfiles#81]
When editing a file using [onlydocuments](https://github.com/humhub-contrib/onlydocuments) module the `updated_at` field is not updated and keeps showing the same value as the `created_at` field.

We're using Files module version 0.11.17, Onlydocuments 1.0.3 and Humhub 1.2.8.

**Comment by michael79bxl** [comment]
For me, it's worse, files are not updated at all (they are updated on onlyoffice but not on humhub)

**Comment by luke-** [comment]
Should be fixed.
