### ISSUE TITLE
Move files and folders by drag & drop

### ISSUE THREAD

**Issue by Oremountainflorian** [humhub/cfiles#82]
It would be useful to move one or more files/folders via drag and drop to other folders.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/cfiles/pull/132

**Comment by luke-** [comment]
@yurabakhtin Looks good thanks! Can you please check my PR remark?

**Comment by yurabakhtin** [comment]
@luke- Please read https://github.com/humhub/cfiles/pull/132#discussion_r701245825.

**Comment by luke-** [comment]
@yurabakhtin Thanks!
